name: VariableTime
main: zedly.variabletime.VariableTime
version: 1.0.0
api-version: '1.15'
commands:
  vt:
    description: Allows for access of the /vt command
    usage: /vt <day/night/info/help>
    default: false
permissions:
  variabletime.set:
    description: Allows for changing different time variables.
    default: false
  variabletime.info:
    description: Allows for getting the world time settings.
    default: false
  variabletime.*:
    children:
      variabletime.set: true
      variabletime.info: true
